M48
; DRILL file {KiCad (7.0.0-0)} date Friday, February 24, 2023 at 10:49:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-24T10:49:35-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C1.500
%
G90
G05
T1
X2.1Y-2.8
X6.9Y-2.8
X15.1Y-2.8
X19.9Y-2.8
T2
X3.75Y-9.5
X18.25Y-9.5
T0
M30
